openapi: 3.0.1
info:
  title: Local File Plugin
  description: A plugin that allows GPT to read and write files locally.
  version: 'v1'
servers:
  - url: http://localhost:5010
paths:
  /cli:
    post:
      operationId: executeCLI
      summary: Execute a CLI command
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
      responses:
        '200':
          description: The stdout and stderr from the command
          content:
            application/json:
              schema:
                type: object
                properties:
                  stdout:
                    type: string
                  stderr:
                    type: string
  /execute:
    post:
      operationId: executePython
      summary: Execute Python code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
      responses:
        '200':
          description: The local variables after executing the code
          content:
            application/json:
              schema:
                type: object
